language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sassy-sketching' ]; then cd .. && eval "mv $currentfolder generator-sassy-sketching" && cd generator-sassy-sketching; fi

